### ISSUE TITLE
Small error in Eve.rb

### ISSUE THREAD

**Issue by Kulikuz** [Namasteh/Eve-Bot#62]
In line 69 is a "]" before the comma at the end. Shouldn't be there. Causes an issue which makes it unable to run the Eve bot.

**Comment by Namasteh** [comment]
Line 69 of what? Could you please clarify?

**Comment by Kulikuz** [comment]
See the title of the issue, it's in Eve.rb

**Comment by Namasteh** [comment]
Typo on Line 69 of Eve.rb is fixed. Thank you for bringing that to my attention.
