### ISSUE TITLE
Bitcoin plugin loading

### ISSUE THREAD

**Issue by Kulikuz** [Namasteh/Eve-Bot#63]
![imgur-2015_04_28-23 18 37](https://cloud.githubusercontent.com/assets/7875247/7380761/ffd10f66-edfd-11e4-9fe2-3865cee5cd77.png)
pi@CynPi ~/git/Eve-Bot $ ruby Eve.rb

/home/pi/git/Eve-Bot/bin/plugins.rb:30:in `require_relative': cannot load such file -- /home/pi/git/Eve-Bot/lib/plugins/bitcoin (LoadError)
	from /home/pi/git/Eve-Bot/bin/plugins.rb:30:in `<top (required)>'
	from Eve.rb:4:in `require_relative'
	from Eve.rb:4:in `<main>'

**Comment by Namasteh** [comment]
As EveSix will no longer be supported coming up here soon, I will assist with this bug however I am classifying it as 'wontfix'
Please remove line 30 of /bin/plugins.rb
