### ISSUE TITLE
cannot load such file -- action_view (LoadError)

### ISSUE THREAD

**Issue by Kulikuz** [Namasteh/Eve-Bot#64]
![imgur-2015_04_28-23 31 33](https://cloud.githubusercontent.com/assets/7875247/7380858/c2ef22f8-edfe-11e4-8da7-bde6224f67c3.png)

pi@CynPi ~/git/Eve-Bot $ ruby Eve.rb
/home/pi/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- action_view (LoadError)
	from /home/pi/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/pi/git/Eve-Bot/lib/plugins/reddit.rb:5:in `<top (required)>'
	from /home/pi/git/Eve-Bot/bin/plugins.rb:38:in `require_relative'
	from /home/pi/git/Eve-Bot/bin/plugins.rb:38:in `<top (required)>'
	from Eve.rb:4:in `require_relative'
	from Eve.rb:4:in `<main>'

**Comment by Namasteh** [comment]
Please
>gem install actionview

This will fix your issue

**Comment by Namasteh** [comment]
Added 'actionview' as a dependency in easy install line.
