### ISSUE TITLE
word_game.rb:40: warning: else without rescue is useless

### ISSUE THREAD

**Issue by Kulikuz** [Namasteh/Eve-Bot#65]
pi@CynPi ~/git/Eve-Bot $ ruby Eve.rb
/home/pi/git/Eve-Bot/lib/plugins/word_game.rb:40: warning: else without rescue is useless
/home/pi/git/Eve-Bot/lib/plugins/tag.rb:89: warning: else without rescue is useless
/home/pi/git/Eve-Bot/lib/plugins/coin_query.rb:34: warning: else without rescue is useless
Eve.rb:64:in `block (2 levels) in <main>': uninitialized constant Cinch::Plugins::RelationshipHandler (NameError)
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/cinch-2.2.5/lib/cinch/bot.rb:218:in `configure'
	from Eve.rb:24:in `block in <main>'
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/cinch-2.2.5/lib/cinch/bot.rb:355:in `instance_eval'
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/cinch-2.2.5/lib/cinch/bot.rb:355:in `initialize'
	from Eve.rb:23:in `new'
	from Eve.rb:23:in `<main>'
![imgur-2015_04_28-23 37 01](https://cloud.githubusercontent.com/assets/7875247/7380977/9c0b7c8a-edff-11e4-8a81-6e2076791e86.png)

**Comment by Namasteh** [comment]
This is a warning. You can ignore this.

**Comment by Kulikuz** [comment]
Are you sure that the 4th line is a warning too? Because after it the process exits.

**Comment by Kulikuz** [comment]
That may be related due to me deleting the line with the relationship handler in the plugins file. (See the other Issue I have opened)

**Comment by Namasteh** [comment]
@Kulikuz The fourth line is a different error entirely. Please post that as an issue.
