### ISSUE TITLE
undefined method `requite_relative' for main:Object (NoMethodError)

### ISSUE THREAD

**Issue by Kulikuz** [Namasteh/Eve-Bot#66]
pi@CynPi ~/git/Eve-Bot $ ruby Eve.rb
/home/pi/git/Eve-Bot/bin/plugins.rb:32:in `<top (required)>': undefined method `requite_relative' for main:Object (NoMethodError)
	from Eve.rb:4:in `require_relative'
	from Eve.rb:4:in `<main>'
![imgur-2015_04_28-23 39 20](https://cloud.githubusercontent.com/assets/7875247/7381008/d2c3ca0c-edff-11e4-8aec-59ac22f62a04.png)

**Comment by Namasteh** [comment]
In /bin/plugins.rb change the 't' in 'requite' to 'r' making it; 'require'

**Comment by Kulikuz** [comment]
![imgur-2015_04_28-23 50 11](https://cloud.githubusercontent.com/assets/7875247/7381188/57e07054-ee01-11e4-95db-c17779a6a7b3.png)

**Comment by Namasteh** [comment]
This is a different issue. Please make a new issue for it.
