### ISSUE TITLE
uninitialized constant Cinch::Plugins::RelationshipHandler (NameError)

### ISSUE THREAD

**Issue by Kulikuz** [Namasteh/Eve-Bot#67]
Eve.rb:64:in `block (2 levels) in <main>': uninitialized constant Cinch::Plugins::RelationshipHandler (NameError)
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/cinch-2.2.5/lib/cinch/bot.rb:218:in `configure'
	from Eve.rb:24:in `block in <main>'
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/cinch-2.2.5/lib/cinch/bot.rb:355:in `instance_eval'
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/cinch-2.2.5/lib/cinch/bot.rb:355:in `initialize'
	from Eve.rb:23:in `new'
	from Eve.rb:23:in `<main>'

(4th line on screenshot)
![imgur-2015_04_28-23 54 55](https://cloud.githubusercontent.com/assets/7875247/7381268/014f9d0e-ee02-11e4-8100-e4db5047790d.png)

**Comment by Namasteh** [comment]
You need to add the relationship_handler file to the plugins.rb file again.

**Comment by Kulikuz** [comment]
I did that, but then I get the "cannot load such file" error. See Issue #68.
