### ISSUE TITLE
`require_relative': cannot load such file -- /home/pi/git/Eve-Bot/lib/plugins/config/check_friend (LoadError)

### ISSUE THREAD

**Issue by Kulikuz** [Namasteh/Eve-Bot#68]
pi@CynPi ~/git/Eve-Bot $ ruby Eve.rb 
/home/pi/git/Eve-Bot/lib/plugins/relationship_handler.rb:3:in `require_relative': cannot load such file -- /home/pi/git/Eve-Bot/lib/plugins/config/check_friend (LoadError)
	from /home/pi/git/Eve-Bot/lib/plugins/relationship_handler.rb:3:in `<top (required)>'
	from /home/pi/git/Eve-Bot/bin/plugins.rb:32:in `require_relative'
	from /home/pi/git/Eve-Bot/bin/plugins.rb:32:in `<top (required)>'
	from Eve.rb:4:in `require_relative'
	from Eve.rb:4:in `<main>'
![imgur-2015_04_29-00 17 54](https://cloud.githubusercontent.com/assets/7875247/7381592/33270dfa-ee05-11e4-86b3-21bdc8e969a5.png)

**Comment by Namasteh** [comment]
On line 3 of relationship_handler.rb you need to remove all the 'check_*' require lines and replace them with a single one:
>require_relative "config/check_relationship"
