### ISSUE TITLE
found character that cannot start any token while scanning for the next token at line 2 column 1 (Psych::SyntaxError)

### ISSUE THREAD

**Issue by Kulikuz** [Namasteh/Eve-Bot#69]
/home/pi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/psych.rb:370:in `parse': (docs/userinfo.yaml): found character that cannot start any token while scanning for the next token at line 2 column 1 (Psych::SyntaxError)
	from /home/pi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/psych.rb:370:in `parse_stream'
	from /home/pi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/psych.rb:318:in `parse'
	from /home/pi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/psych.rb:245:in `load'
	from /home/pi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/psych.rb:464:in `block in load_file'
	from /home/pi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/psych.rb:464:in `open'
	from /home/pi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/psych.rb:464:in `load_file'
	from /home/pi/git/Eve-Bot/lib/plugins/chanop_cp.rb:44:in `initialize'
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/cinch-2.2.5/lib/cinch/plugin_list.rb:11:in `new'
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/cinch-2.2.5/lib/cinch/plugin_list.rb:11:in `register_plugin'
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/cinch-2.2.5/lib/cinch/plugin_list.rb:16:in `block in register_plugins'
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/cinch-2.2.5/lib/cinch/plugin_list.rb:16:in `each'
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/cinch-2.2.5/lib/cinch/plugin_list.rb:16:in `register_plugins'
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/cinch-2.2.5/lib/cinch/bot.rb:239:in `start'
	from Eve.rb:112:in `<main>'
![imgur-2015_04_29-00 24 25](https://cloud.githubusercontent.com/assets/7875247/7381664/1d215550-ee06-11e4-8018-daaa00d6fe9f.png)

**Comment by Namasteh** [comment]
This is a strange one, try deleting docs/userinfo.yaml and then create a 0byte file called userinfo.yaml again. Let me know in this thread what happens.

**Comment by Kulikuz** [comment]
/home/pi/git/Eve-Bot/lib/plugins/twitter_status.rb:23:in `block in initialize': [DEPRECATION] #oauth_token= is deprecated. Use #access_token= instead.
/home/pi/git/Eve-Bot/lib/plugins/twitter_status.rb:24:in `block in initialize': [DEPRECATION] #oauth_token_secret= is deprecated. Use #access_token_secret= instead.
/home/pi/.rvm/gems/ruby-2.2.1/gems/twitter-5.14.0/lib/twitter/rest/response/raise_error.rb:15:in `on_complete': Invalid or expired token. (Twitter::Error::Unauthorized)
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.1/lib/faraday/response.rb:9:in `block in call'
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.1/lib/faraday/request/url_encoded.rb:15:in `call'
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.1/lib/faraday/request/multipart.rb:14:in `call'
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/twitter-5.14.0/lib/twitter/rest/request/multipart_with_file.rb:17:in `call'
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.1/lib/faraday/connection.rb:140:in `get'
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/twitter-5.14.0/lib/twitter/rest/request.rb:33:in `perform'
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/twitter-5.14.0/lib/twitter/rest/utils.rb:51:in `perform_request'
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/twitter-5.14.0/lib/twitter/rest/utils.rb:96:in `perform_request_with_objects'
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/twitter-5.14.0/lib/twitter/rest/utils.rb:140:in `objects_from_response_with_user'
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/twitter-5.14.0/lib/twitter/rest/timelines.rb:49:in `user_timeline'
	from /home/pi/git/Eve-Bot/lib/plugins/twitter_status.rb:113:in `refresh_cache'
	from /home/pi/git/Eve-Bot/lib/plugins/twitter_status.rb:31:in `block (2 levels) in initialize'
	from /home/pi/git/Eve-Bot/lib/plugins/twitter_status.rb:31:in `each'
	from /home/pi/git/Eve-Bot/lib/plugins/twitter_status.rb:31:in `block in initialize'
	from /home/pi/git/Eve-Bot/lib/plugins/twitter_status.rb:29:in `each_pair'
	from /home/pi/git/Eve-Bot/lib/plugins/twitter_status.rb:29:in `initialize'
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/cinch-2.2.5/lib/cinch/plugin_list.rb:11:in `new'
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/cinch-2.2.5/lib/cinch/plugin_list.rb:11:in `register_plugin'
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/cinch-2.2.5/lib/cinch/plugin_list.rb:16:in `block in register_plugins'
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/cinch-2.2.5/lib/cinch/plugin_list.rb:16:in `each'
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/cinch-2.2.5/lib/cinch/plugin_list.rb:16:in `register_plugins'
	from /home/pi/.rvm/gems/ruby-2.2.1/gems/cinch-2.2.5/lib/cinch/bot.rb:239:in `start'
	from Eve.rb:112:in `<main>'

**Comment by Namasteh** [comment]
Comment out every line containing Twitter information in Eve.rb and plugins.rb. These Twitter plugins are deprecated

**Comment by Namasteh** [comment]
This issue now has a fix and is being pushed to the v6.5.5 release. 

https://github.com/Namasteh/Eve-Bot/commit/c70c63b2a06b6cac3035bdcd5d127dffb79d225e
