### ISSUE TITLE
/home/pi/git/Eve-Bot/lib/plugins/greeting.rb:139:in `goodbye': undefined method `name' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by Kulikuz** [Namasteh/Eve-Bot#71]
Issue's in this line: "return unless config[:enabled_channels].include?(m.channel.name)"

**Comment by Namasteh** [comment]
What issue? Can I get a screen shot or a copy pasta?

**Comment by Kulikuz** [comment]
"/home/pi/git/Eve-Bot/lib/plugins/greeting.rb:139:in `goodbye': undefined method `name' for nil:NilClass (NoMethodError)" This came up after someone left the channel. When I leave it now it works.

**Comment by Namasteh** [comment]
This issue was fixed on commit: https://github.com/Namasteh/Eve-Bot/commit/7c9372df778896f10cf5b5ed24334ccfa3d260cd
