### ISSUE TITLE
[eve7] EOF after setup.rb

### ISSUE THREAD

**Issue by Kulikuz** [Namasteh/Eve-Bot#73]
http://i.imgur.com/gZSPhW1.png

**Comment by Namasteh** [comment]
This is a known issue. Until a patch for this is released, please ^C and then run install.rb manually. I apologize, but it -is- alpha :smile:

**Comment by Namasteh** [comment]
Issue resolved in https://github.com/Namasteh/Eve-Bot/commit/6dac5b38f15821b7823b613dab2c642386ca776a (click for more details on cause)
