### ISSUE TITLE
[eve7] Install script error

### ISSUE THREAD

**Issue by Kulikuz** [Namasteh/Eve-Bot#75]
After installing Eve7 using $ sudo ruby install.rb by accident I removed the eve7 installed folder using $ rm -rf ~/Eve7

Tried to execute $ ruby install.rb without sudo then and got this:

http://i.imgur.com/ij5P8OE.png
http://i.imgur.com/Iw0Km1X.png

The files in the extracted Eve7 archive still look fine to me: http://i.imgur.com/mBbemhc.png

**Comment by Namasteh** [comment]
Did you attempt `sudo rm -fr ~/Eve7`?

**Comment by Kulikuz** [comment]
Yes of course, sorry I forgot the "sudo".

**Comment by Namasteh** [comment]
[This picture of a directory you gave me](http://i.imgur.com/mBbemhc.png) does not match the directory [that eve7 was installing in according to this picture](http://i.imgur.com/ij5P8OE.png).

Please submit the output of:
`$ ls /home/pi/eve7`

**Comment by Kulikuz** [comment]
This is the output for Eve7: http://i.imgur.com/Iw0Km1X.png
The picture you've linked first is $ ls for the directory I have extracted the archieve, just for you to see that the files are in there.

**Comment by Namasteh** [comment]
Please try running the following:

`$ sudo rm -rf /home/pi/eve7`
`$ cd <github directory>`
`$ ruby install.rb`

**Comment by Kulikuz** [comment]
That worked. I did the exact same thing before, but instead of $ cd <github directory> I did $ ruby <github directory>/install.rb - But I don't think that caused the errors.

**Comment by Namasteh** [comment]
Do you mind if I make a final post with all the pictures easily visible so if future users have this issue they have a nice guide?

**Comment by Kulikuz** [comment]
No problem
